#!/bin/bash

<<COMMENTS
Author: Jordan Wallschlaeger
Partner: Sawyer Hansen
01PC
Network Recon program that does ping sweeps and port scans based on the input of the user. Also
prints the resualts and has the option to clear them. Netcat was used for port sweep as nmap was 
prohibitted from directions. 
COMMENTS

function exitfunc () {
	echo "Now exitting the Program"
	exit
}

function menu () {
	clear
	echo "------------Main Menu-----------"
	echo "1) Ping Sweep 3) Print Results"
	echo "2) Port Scan 4) Exit"
	echo "Please choose a function to do"
	read funcnum
	case $funcnum in
		1) pingsweep ;;
		2) portscan ;;
		3) print_results ;;
		4) exitfunc ;;
		*) echo "Not a valid option";;
	esac
}

function pingsweep () {
	clear
	echo "-----------Ping Sweep-----------"
	read -p "Enter the network prefix (x.x.x): " prefix
	echo "Ping results on prefix ${prefix}: " | tee -a pingresults.txt
	for (( host=0; host<=255; host++)); do
		address="${prefix}.${host}"
		echo "Pinging host ${address}..."
		ping -4c 1 -W 1 -q $address > /dev/null
		if [ $? -eq 0 ]; then
			echo "Host ${address} is active." | tee -a pingresults.txt
		fi
	done
	echo -e "\n\n"
	menu	
}

function portscan () {
	clear
	echo "-----------Port Scan------------"
	read -p "Enter the IP address to scan: " ip_address
	read -p "Enter the starting port number: " start_port
	read -p "Enter the ending port number: " end_port
	echo -e "Scanning ports $start_port to $end_port on $ip_address\n" | tee -a portscanresults.txt
	for (( port=$start_port; port<=$end_port; port++ ))
	do
		nc -zw 1 $ip_address $port
		if [ $? -eq 0 ]; then
	  		echo "Port ${port} is open" | tee -a portscanresults.txt
		elif [ $? -eq 1 ]; then
	  		echo "Port ${port} is closed" | tee -a portscanresults.txt
	  	fi
	done
	echo -e "\n\n"
	menu
}

function print_results () {
	clear
	echo "-----------Print Results-----------"
	select print in "Print Ping Sweep Results" "Print Port Scan Results" "Clear Ping Sweep Results" "Clear Port Scan Results" "Back"; do
		case $print in
			"Print Ping Sweep Results")
				cat ./pingresults.txt
				print_results;;
			"Print Port Scan Results")
				cat ./portscanresults.txt
				print_results;;
			"Clear Ping Sweep Results")
				rm ./pingresults.txt
				print_results;;
			"Clear Port Scan Results")
				rm ./portscanresults.txt
				print_results;;
			"Back")
				menu;;
			*)
				echo "Invalid option"
		esac
	done
}
	


menu

